set -g default-shell /bin/zsh
set -g escape-time 0
set -g pane-active-border-style fg=default
set -g set-clipboard on
set -g status-position top
set -g status-style bg=default
set -sg terminal-overrides ",*:RGB"
setw -g mode-keys vi

# Move with hjkl, swap with HJKL
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind H swap-pane -s '{left-of}'
bind J swap-pane -s '{down-of}'
bind K swap-pane -s '{up-of}'
bind L swap-pane -s '{right-of}'

# Vim-style visual yank and paste
bind v copy-mode
bind p paste-buffer
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel

set -s command-alias[100] splith='split-window -v'
set -s command-alias[101] splitv='split-window -h'
set -s command-alias[102] splithf='split-window -vf'
set -s command-alias[103] splitvf='split-window -hf'
set -s command-alias[104] evenh='select-layout even-vertical'
set -s command-alias[105] evenv='select-layout even-horizontal'
set -s command-alias[106] resl='resize-pane -L'
set -s command-alias[107] resr='resize-pane -R'
set -s command-alias[108] resu='resize-pane -U'
set -s command-alias[109] resd='resize-pane -D'
set -s command-alias[110] soc='source-file ~/.config/tmux/tmux.conf'
set -s command-alias[111] spt='swap-pane -t'
